/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TourTourIdRouteImport } from './routes/tour/$tourId'
import { Route as AttractionsTourIdAttractionIdRouteImport } from './routes/attractions/$tourId.$attractionId'

const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTourIdRoute = TourTourIdRouteImport.update({
  id: '/tour/$tourId',
  path: '/tour/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsTourIdAttractionIdRoute =
  AttractionsTourIdAttractionIdRouteImport.update({
    id: '/attractions/$tourId/$attractionId',
    path: '/attractions/$tourId/$attractionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theme': typeof ThemeRoute
  '/tour/$tourId': typeof TourTourIdRoute
  '/attractions/$tourId/$attractionId': typeof AttractionsTourIdAttractionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theme': typeof ThemeRoute
  '/tour/$tourId': typeof TourTourIdRoute
  '/attractions/$tourId/$attractionId': typeof AttractionsTourIdAttractionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theme': typeof ThemeRoute
  '/tour/$tourId': typeof TourTourIdRoute
  '/attractions/$tourId/$attractionId': typeof AttractionsTourIdAttractionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/theme'
    | '/tour/$tourId'
    | '/attractions/$tourId/$attractionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/theme' | '/tour/$tourId' | '/attractions/$tourId/$attractionId'
  id:
    | '__root__'
    | '/'
    | '/theme'
    | '/tour/$tourId'
    | '/attractions/$tourId/$attractionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThemeRoute: typeof ThemeRoute
  TourTourIdRoute: typeof TourTourIdRoute
  AttractionsTourIdAttractionIdRoute: typeof AttractionsTourIdAttractionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$tourId': {
      id: '/tour/$tourId'
      path: '/tour/$tourId'
      fullPath: '/tour/$tourId'
      preLoaderRoute: typeof TourTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions/$tourId/$attractionId': {
      id: '/attractions/$tourId/$attractionId'
      path: '/attractions/$tourId/$attractionId'
      fullPath: '/attractions/$tourId/$attractionId'
      preLoaderRoute: typeof AttractionsTourIdAttractionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThemeRoute: ThemeRoute,
  TourTourIdRoute: TourTourIdRoute,
  AttractionsTourIdAttractionIdRoute: AttractionsTourIdAttractionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
